### ISSUE TITLE
[Bug]Browser download fails

### ISSUE THREAD

**Issue by ubuygold** [CheshireCaat/playwright-with-fingerprints#2]
When running example code:
```
import { plugin } from "playwright-with-fingerprints"

(async () => {
    // Get a fingerprint from the server:
    const fingerprint = await plugin.fetch('', {
        tags: ['Microsoft Windows', 'Chrome'],
    })

    // Apply fingerprint:
    plugin.useFingerprint(fingerprint)

    // Launch the browser instance:
    const browser = await plugin.launch()

    // The rest of the code is the same as for a standard `playwright` library:
    const page = await browser.newPage()
    await page.goto('https://google.com')

    // Print the browser viewport size:
    console.log(
        'Viewport:',
        await page.evaluate(() => ({
            deviceScaleFactor: window.devicePixelRatio,
            width: document.documentElement.clientWidth,
            height: document.documentElement.clientHeight,
        }))
    )

    await browser.close()
})()
```
Found error:
```
The browser is downloading - this may take some time.
C:\Users\xxx\Coding\xx\node_modules\bas-remote-node\src\services\socket.js:101
    this._ws.removeAllListeners();
             ^

TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at SocketService.close (C:\Users\xxx\Coding\xx\node_modules\bas-remote-node\src\services\socket.js:101:14)
    at BasRemoteClient.close (C:\Users\xxx\Coding\xx\node_modules\bas-remote-node\src\index.js:290:20)
    at C:\Users\xxx\Coding\xx\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:30:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Node.js version: 18
ESM + TypeScript Mode

**Comment by CheshireCaat** [comment]
This information is not enough. What plugin version are you using?

**Comment by ubuygold** [comment]
Upgraded just now 
Here's the package.json
```
{
  "name": "xx",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@faker-js/faker": "^7.6.0",
    "axios": "^1.3.4",
    "better-queue": "^3.8.12",
    "free-proxy-finder": "^1.0.1",
    "playwright": "^1.31.2",
    "playwright-with-fingerprints": "^1.1.5",
    "typescript": "^4.9.5"
  },
  "type": "module",
  "scripts": {
    "dev": "ts-node-esm"
  },
  "devDependencies": {
    "@types/better-queue": "^3.8.3",
    "@types/node": "^18.15.0"
  }
}
```

**Comment by CheshireCaat** [comment]
OK, thanks, i'll take a look.

**Comment by CheshireCaat** [comment]
Please try to use the latest version - `1.1.6`. Also, before the next run, remove the `data` folder from your script's working directory.

**Comment by ubuygold** [comment]
Thx, it works.
