### ISSUE TITLE
Running on MacOS

### ISSUE THREAD

**Issue by opahopa** [CheshireCaat/playwright-with-fingerprints#22]
Hi!
Getting this error `Unsupported OS platform for named mutex.` when trying to run on MacOS Monterey 12.6

```
/*****/*****/projects/browser-tests/playwright-with-fingerprints/node_modules/.pnpm/browser-with-fingerprints@1.5.3/node_modules/browser-with-fingerprints/src/plugin/mutex/index.js:7
    throw new Error('Unsupported OS platform for named mutex.');
    ^

Error: Unsupported OS platform for named mutex.
    at Object.<anonymous> (/Users/*****/projects/browser-tests/playwright-with-fingerprints/node_modules/.pnpm/browser-with-fingerprints@1.5.3/node_modules/browser-with-fingerprints/src/plugin/mutex/index.js:7:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/*****/projects/browser-tests/playwright-with-fingerprints/node_modules/.pnpm/browser-with-fingerprints@1.5.3/node_modules/browser-with-fingerprints/src/plugin/index.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

in `plugin` dir there are mutex plugins for Windows. What are those exactly? any advise which one to use for MacOS or i have to go through the `browser-with-fingerprints` and implement some other generic node mutex?

**Comment by bablosoft** [comment]
Only Windows is supported.
