### ISSUE TITLE
InvalidEngineError when reusing working directory

### ISSUE THREAD

**Issue by victornor** [CheshireCaat/playwright-with-fingerprints#42]
How do i deal with this, which happens constantly?
I've deleted the engine many times and the error returns after just a few re-uses of the work directory.

> Uncaught InvalidEngineError InvalidEngineError: Unable to start engine process (code: 3221225781)
This could be due to the fact that the engine was not downloaded or unpacked correctly.
Try completely deleting the engine folder and restarting the code until it completes.
If this does not help, open an issue with a detailed description of the problem.
    at <anonymous> (.....\node_modules\bas-remote-node\src\services\engine.js:117:17)
    at exithandler (child_process:427:5)
    at emit (events:513:28)
    at maybeClose (internal/child_process:1091:16)
    at <anonymous> (internal/child_process:449:11)
    at emit (events:513:28)
    at <anonymous> (net:322:12)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- PIPEWRAP ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at <anonymous> (internal/child_process:1015:20)
    at getValidStdio (internal/child_process:991:11)
    at ChildProcess.spawn (internal/child_process:355:11)
    at spawn (child_process:757:9)
    at execFile (child_process:348:17)
    at _runEngineProcess (....\node_modules\bas-remote-node\src\services\engine.js:111:21)
    at start (.....\node_modules\bas-remote-node\src\services\engine.js:58:10)
    at processTicksAndRejections (internal/process/task_queues:95:5)

**Comment by CheshireCaat** [comment]
The engine may be damaged if you use the same folder in different processes.

**Comment by CheshireCaat** [comment]
Please provide a minimal code example on which the problem can be reproduced.

**Comment by CheshireCaat** [comment]
@victornor greetings, have you solved the problem?
